#!/usr/bin/env node
/* ============================================================
   tools/guide-gs.mjs — the command-word guide, for the reflection system's student dashboard.

   The guide has ONE master: ../bio-english-lab-source/guide.master.json. This site's "Command
   words" page is built from it (tools/build.mjs). This tool makes the dashboard's copy:

     node tools/guide-gs.mjs <path to the live 4_StudentDashboardHTML.gs>

   writes ../bio-english-lab-source/out/reflection/
     6_QuestionGuide.gs          NEW file for the reflection project: the guide as data, plus
                                 qsGuideLegacy_(), which turns it into the dashboard's own shapes
     4_StudentDashboardHTML.gs   a COPY of the given file with small, exact edits: two blocks that
                                 use the guide when 6_QuestionGuide.gs is present (and change nothing
                                 when it is not), card counts that follow the data, and the corrected
                                 decoder and worked-example sentences
   Every edit must find its original text exactly once, or the tool stops and changes nothing —
   so a dashboard that has moved on since is never patched blind.
   ============================================================ */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.resolve(HERE, '..', '..', 'bio-english-lab-source');
/* The reflection system's own folders: ONE copy of each file, in Daniel's two synced project
   folders, never a third in this source tree. Both are written, because they are kept identical. */
const REFLECT = [
  '/Users/NLCS/Library/CloudStorage/OneDrive-Personal/NLCS/IGCSE/AppScript/AppScript REFLECTION System/Claude code',
  '/Users/NLCS/Library/CloudStorage/OneDrive-Personal/NLCS/IGCSE/AppScript/AppScript REFLECTION System/Final code'
].filter(d => fs.existsSync(d));
const OUT = REFLECT.length ? REFLECT : [path.join(SRC, 'out', 'reflection')];
function writeReflection(name, text) {
  OUT.forEach(d => { fs.mkdirSync(d, { recursive: true }); fs.writeFileSync(path.join(d, name), text); console.log('✓ written: ' + path.join(d, name)); });
}
const G = JSON.parse(fs.readFileSync(path.join(SRC, 'guide.master.json'), 'utf8'));
const dashPath = process.argv[2];
if (!dashPath) { console.error('usage: node tools/guide-gs.mjs <4_StudentDashboardHTML.gs>'); process.exit(1); }
const dash = fs.readFileSync(dashPath, 'utf8');
if (/BIO ENGLISH LAB EDITS APPLIED/.test(dash)) {
  console.error('That dashboard already carries these edits — it is the patched file, not the original.\n' +
    'Point this at an unpatched 4_StudentDashboardHTML.gs, or take the previous version from OneDrive history.');
  process.exit(1);
}

/* ---------- 6_QuestionGuide.gs ---------- */
const data = {
  commands: G.commands.map(c => ({ word: c.word, official: c.official || '', plain: c.plain || '', pattern: c.pattern, status: c.status || '' })),
  patterns: G.patterns.map(p => ({ id: p.id, group: p.group, order: p.order, freq: p.freq, title: p.title, strategy: p.strategy || '', signature: p.signature || '',
    steps: p.steps || [], pitfalls: p.pitfalls || [], note: p.cambridgeNote || '', commands: p.commands || [],
    example: p.example ? { source: p.example.source, stem: p.example.stem, marks: p.example.marks, markScheme: p.example.markScheme || [], guidance: p.example.guidance || [], model: p.example.model || '' } : null })),
  mistakes: G.mistakes.map(m => ({ id: m.id, title: m.title, body: m.body, source: m.source }))
};
const gs = `/**
 * 6_QuestionGuide.gs — the command-word guide ("How to answer" tab), as data.
 * ─────────────────────────────────────────────────────────────────
 * GENERATED by Bio English Lab (labs/bio-english-lab/tools/guide-gs.mjs) from its master,
 * guide.master.json, on ${new Date().toISOString().slice(0, 10)}. Bio English Lab's "Command words" page is built from
 * the same master, so the two always give students the same advice. Edit the master, not this file.
 *
 * 4_StudentDashboardHTML.gs uses this file when it is present (qsGuideLegacy_ below turns the
 * guide into the dashboard's own card shapes). Remove this file and the dashboard falls back to
 * the cards written inside 4_StudentDashboardHTML.gs.
 *
 * Every example is a real Cambridge 0610 question; its mark-scheme lines are as printed.
 * ─────────────────────────────────────────────────────────────────
 */
var QS_GUIDE = ${JSON.stringify(data, null, 1)};

/* The dashboard's shapes, built from QS_GUIDE. \`old\` is the dashboard's own data: each card keeps its
   emoji, star rating, diagram and year tip, and keeps its figure only when its example is unchanged. */
function qsGuideLegacy_(old) {
  old = old || {};
  function esc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
  function key(cite) {                         /* "0610/41 May/June 2024 Q5(a)" and "…0610/41, May/June 2024, Question 5(a)" are one question */
    var s = String(cite || ''), m = s.match(/0610\\/(\\d\\d)/), y = s.match(/(20\\d\\d)/), q = s.match(/(?:Q|Question)\\s*([0-9]+[a-z()ivx]*)/i);
    var ses = /march|feb/i.test(s) ? 'm' : /june|may/i.test(s) ? 's' : /nov|oct/i.test(s) ? 'w' : '';
    return m && y && q ? m[1] + ses + y[1] + q[1].replace(/\\s/g, '') : s;
  }
  var oldCards = {};
  (old.QS_PATTERNS || []).concat(old.QS_SKILLS || []).forEach(function (c) { oldCards[c.num] = c; });
  var EMOJI = { 22: '🔮', 23: '✏️', 24: '🕸️' };
  /* The same guide, and the practice for it, are one click apart: each card links to that command
     word on Bio English Lab, which is built from this very master. */
  var SITE = 'https://nlcsbiology.com/bio-english-lab/#/commands';
  var firstWord = {};
  (QS_GUIDE.commands || []).forEach(function (c) { if (c.pattern && !firstWord[c.pattern]) firstWord[c.pattern] = c.word; });
  function card(p) {
    var o = oldCards[p.id] || {}, ex = p.example;
    var same = ex && o.ex && key(o.ex.cite) === key(ex.source);
    var ms = '';
    if (ex) {
      var lines = ex.markScheme.slice(), prefix = '';
      if (lines.length && /^(any \\w+ from|total of|max \\w+ from)/i.test(lines[0])) prefix = lines.shift().replace(/:?\\s*$/, ': ');
      ms = prefix + lines.map(function (l) { return esc(String(l).replace(/\\s*;\\s*$/, '')); }).join(' <b>;</b> ') +
           (ex.guidance.length ? ' <b>;</b> <i>Guidance: ' + ex.guidance.map(esc).join(' · ') + '</i>' : '');
    }
    var out = {
      num: p.id, freq: p.freq || o.freq || 1, em: o.em || EMOJI[p.id] || '📌',
      name: p.title, tag: p.strategy, sig: p.signature,
      app: p.steps.map(esc), watch: p.pitfalls.map(esc), note: p.note,
      ex: ex ? { cite: ex.source, stem: esc(ex.stem) + (ex.marks ? ' <b>[' + ex.marks + ']</b>' : ''), ms: ms, exemplar: esc(ex.model) }
              : (o.ex || { cite: '', stem: '', ms: '' }),
      also: o.also || '',
      practise: SITE + (firstWord[p.id] ? '/' + encodeURIComponent(String(firstWord[p.id]).toLowerCase()) : '')
    };
    if (same && o.ex.figRef) out.ex.figRef = o.ex.figRef;
    if (o.diagram) out.diagram = o.diagram;
    if (o.yearTip) out.yearTip = o.yearTip;
    if (o.seeAlso) out.seeAlso = o.seeAlso;
    return out;
  }
  function byOrder(a, b) { return (a.order || 0) - (b.order || 0); }
  var cmdDesc = {}, cmdLink = {};
  QS_GUIDE.commands.forEach(function (c) { if (c.plain) cmdDesc[c.word] = c.plain; if (c.pattern) cmdLink[c.word] = c.pattern; });
  return {
    CMD_DESCRIPTIONS: cmdDesc,
    CMD_TO_PATTERN: cmdLink,
    QS_PATTERNS: QS_GUIDE.patterns.filter(function (p) { return p.group === 'command'; }).sort(byOrder).map(card),
    QS_SKILLS: QS_GUIDE.patterns.filter(function (p) { return p.group === 'skill'; }).sort(byOrder).map(card),
    QS_MISTAKES: QS_GUIDE.mistakes.map(function (m, i) {
      var was = (old.QS_MISTAKES || [])[i] || {};
      return { em: was.em || '⚠️', title: m.title, body: esc(m.body) + '<br><span style="font-size:11px;color:#6e7681">' + esc(m.source) + '</span>' };
    })
  };
}
`;
writeReflection('6_QuestionGuide.gs', gs);

/* Applying the edits twice is impossible by construction — each `from` is gone after the first
   pass — but the error would be cryptic. The written file carries a marker, and finding it here
   means somebody pointed this tool at an already-patched dashboard. */
const MARK = 'BIO ENGLISH LAB EDITS APPLIED';

/* ---------- the exact edits to a copy of the dashboard ---------- */
const edits = [];
function edit(name, from, to) { edits.push({ name, from, to }); }
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const js = s => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'");

edit('?tab=commands opens the dashboard on that tab',
  "    `})();` +\n\n    `</script></body></html>`;",
  `    \`})();\` +\n\n    /* ?tab=commands (or any tab id) opens the dashboard on that tab: Bio English Lab links a student\n       straight to the command words that cost them marks. Waits for the tab to exist, then switches. */\n    \`(function(){if(!(window.google&&google.script&&google.script.url))return;\` +\n    \`google.script.url.getLocation(function(l){var t=l&&l.parameter&&l.parameter.tab;if(!t)return;var n=0;\` +\n    \`(function go(){if(document.getElementById("tab-"+t)&&typeof showTab==="function"){showTab(t)}else if(n++<50){setTimeout(go,200)}})()})})();\` +\n\n    \`</script></body></html>\`;`);

edit('each card links to its practice on Bio English Lab',
  `            '<div class="pc-section"><h6>Cambridge note</h6><p>' + escH(p.note) + '</p></div>' +`,
  `            '<div class="pc-section"><h6>Cambridge note</h6><p>' + escH(p.note) + '</p></div>' +
            /* one guide, one place to practise it: the site is built from the same master */
            (p.practise ? '<div class="pc-section"><h6>Practise it</h6><p><a href="' + escH(p.practise) +
              '" target="_blank" rel="noopener">Practise this command word on Bio English Lab</a></p></div>' : '') +`);

edit('use the guide for the command-word maps',
  `  // ── Command word performance (sorted by weakness score — most marks lost first) ──`,
  `  /* ONE guide for this dashboard and Bio English Lab (6_QuestionGuide.gs, generated from the same
     master as the site's Command words page). Without that file, the maps above are used. */
  if (typeof qsGuideLegacy_ === 'function') {
    try { var _QG1 = qsGuideLegacy_({}); CMD_DESCRIPTIONS = _QG1.CMD_DESCRIPTIONS; CMD_TO_PATTERN = _QG1.CMD_TO_PATTERN; }
    catch (e_qg1) { Logger.log('question guide (commands) not applied: ' + e_qg1); }
  }

  // ── Command word performance (sorted by weakness score — most marks lost first) ──`);
edit('use the guide for the pattern cards and mistakes',
  `  var FIGURE_IMAGES = {`,
  `  /* ONE guide for this dashboard and Bio English Lab (6_QuestionGuide.gs). The cards above stay as the
     fallback, and lend each new card its emoji, stars, diagram and year tip (and its figure, when the
     example is unchanged). */
  if (typeof qsGuideLegacy_ === 'function') {
    try {
      var _QG2 = qsGuideLegacy_({ QS_PATTERNS: QS_PATTERNS, QS_SKILLS: QS_SKILLS, QS_MISTAKES: QS_MISTAKES });
      QS_PATTERNS = _QG2.QS_PATTERNS; QS_SKILLS = _QG2.QS_SKILLS; QS_MISTAKES = _QG2.QS_MISTAKES;
    } catch (e_qg2) { Logger.log('question guide (cards) not applied: ' + e_qg2); }
  }

  var FIGURE_IMAGES = {`);
edit('card count follows the data (command words)', `12 Question Patterns (Command Words)</div>'`, `' + QS_PATTERNS.length + ' Question Patterns (Command Words)</div>'`);
edit('card count follows the data (skills)', `9 Skills Questions (Drawings, Graphs, Tables, Genetics, MCQ…)</div>'`, `' + QS_SKILLS.length + ' Skills Questions (Drawings, Graphs, Tables, Genetics, MCQ…)</div>'`);
edit('hero claim', `'Every example below is sourced from a real Cambridge 0610 Paper 4 from May/June or Oct/Nov 2022\\u20132025.</p>'`,
  `'Every example is a real Cambridge 0610 question (Paper 4 or Paper 6) with its real mark scheme. The same guide is on Bio English Lab.</p>'`);
const D = Object.fromEntries(G.decoder.map(d => [d.n, d]));
edit('decoder 1', `'<p>Tells you what to do. <em>State</em>, <em>describe</em> and <em>explain</em> all need different kinds of answer.</p>' +
        '<div class="qs-cue">Look for: usually the first verb (action word) in the question.</div></div>'`,
  `'<p>${js(esc(D[1].what))}</p>' +
        '<div class="qs-cue">Look for: ${js(esc(D[1].cue))}</div></div>'`);
edit('decoder 3', `'<p>Whether your answer must use numbers or labels from the question (e.g. from a graph, table, or diagram).</p>' +
        '<div class="qs-cue">Look for: \\u201cusing the information in Fig.\\u201d / \\u201cfrom Fig. 5.1\\u201d.</div></div>'`,
  `'<p>${js(esc(D[3].what))}</p>' +
        '<div class="qs-cue">Look for: ${js(esc(D[3].cue))}</div></div>'`);
edit('decoder 4', `'<p>Special rules in the question: e.g. \\u201cin your own words\\u201d, \\u201cother than X\\u201d, \\u201cnot including Y\\u201d.</p>' +
        '<div class="qs-cue">Look for: italic words, or phrases like \\u201cother than\\u201d.</div></div>'`,
  `'<p>${js(esc(D[4].what))}</p>' +
        '<div class="qs-cue">Look for: ${js(esc(D[4].cue))}</div></div>'`);
const W = G.decoderWorkedExample, WS = Object.fromEntries(W.signals.map(s => [s.n, s.text]));
edit('worked example, signal 3', `<div>\\u201cshown in Fig. 5.1\\u201d means your answer must be about THIS graph, not general theory. The mark scheme for THIS question does not require you to write specific numbers, but adding numbers makes a stronger answer.</div>`,
  `<div>${js(esc(WS[3]))}</div>`);
edit('worked example, signal 4', `<div>The question says \\u201cthe results\\u201d (plural \\u2014 more than one) AND mentions BOTH \\u201cupper and lower surfaces\\u201d. So you must describe BOTH lines on the graph, not just one of them.</div>`,
  `<div>${js(esc(WS[4]))}</div>`);
edit('worked example, tip', `'<div class="qs-worked-tip"><b>Tip.</b> If the question says <em>\\u201cUsing the information in Fig./Table\\u201d</em>, you MUST quote numbers from the graph or table. Answers without numbers will lose marks.</div>'`,
  `'<div class="qs-worked-tip"><b>Tip.</b> ${js(esc(W.tip))}</div>'`);

let patched = dash, report = [];
for (const e of edits) {
  const n = patched.split(e.from).length - 1;
  if (n !== 1) { console.error('✗ "' + e.name + '": the original text was found ' + n + ' times (need exactly 1). Nothing written.'); process.exit(1); }
  patched = patched.replace(e.from, () => e.to);
  report.push('✓ ' + e.name);
}
/* the worked example's own model answer (it had "increases … becomes constant", not the scheme's words) */
const mOld = patched.match(/<div class="pc-exemplar" style="margin-top:12px"><div class="pc-exemplar-head">\\u2705 Model answer \(full marks\)<\/div><div class="pc-exemplar-body">[^']*<\/div><\/div>/);
if (mOld) { patched = patched.replace(mOld[0], () => `<div class="pc-exemplar" style="margin-top:12px"><div class="pc-exemplar-head">\\u2705 Model answer (full marks)</div><div class="pc-exemplar-body">${js(esc(W.model))}</div></div>`); report.push('✓ worked example, model answer'); }
writeReflection('4_StudentDashboardHTML.gs',
  '/* ' + MARK + ' — ' + new Date().toISOString().slice(0, 10) + ': the command-word guide comes from 6_QuestionGuide.gs.\n   Regenerate from an UNPATCHED dashboard only (labs/bio-english-lab/tools/guide-gs.mjs). */\n' + patched);
console.log(report.join('\n'));
